FROM ubuntu:16.04

RUN  sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
RUN  apt-get clean
RUN  apt-get update
RUN  apt-get install -y software-properties-common

RUN  apt-get install -y gcc g++

RUN  apt-get install -y openjdk-8-jdk && \
     apt-get install -y ant && \
     apt-get clean;
RUN  apt-get install ca-certificates-java && \
     apt-get clean && \
     update-ca-certificates -f;
ENV  PATH $PATH:$JAVA_HOME/bin
RUN  export JAVA_HOME

RUN apt-get install -y python-software-properties
RUN  add-apt-repository ppa:deadsnakes/ppa
RUN  apt-get install python3

RUN  apt-get -y install golang

RUN add-apt-repository ppa:chris-lea/node.js
RUN apt-get -y install nodejs
RUN apt-get -y install npm
RUN nodejs -v